/**
 *  THE CONTENT OF THIS FILE IS AUTOGENERATED BY THE CLI. DONT EDIT IT DIRECTLY
 *  If you need to edit the template, to to libs/cli/src/commands/feature.ts
 */
import { createTypedContainer } from '@dungeon-crawler/shared';

import { authProviders } from './features/auth/auth.providers';
import { coreProviders } from './features/core/core.providers';

import { userProviders } from './features/user/user.providers';

const dependencies = {
  ...authProviders,
  ...coreProviders,
  ...userProviders
};

export const container = createTypedContainer(dependencies);
export type Container = typeof container;
