/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArenaGrid: typeof import('./src/features/arena/components/ArenaGrid.vue')['default']
    ArenaList: typeof import('./src/features/arena/components/ArenaList.vue')['default']
    ArkDialog: typeof import('@ark-ui/vue')['Dialog']
    ArkDialogBackdrop: typeof import('@ark-ui/vue')['DialogBackdrop']
    ArkDialogCloseTrigger: typeof import('@ark-ui/vue')['DialogCloseTrigger']
    ArkDialogContainer: typeof import('@ark-ui/vue')['DialogContainer']
    ArkDialogContent: typeof import('@ark-ui/vue')['DialogContent']
    ArkDialogDescription: typeof import('@ark-ui/vue')['DialogDescription']
    ArkDialogTitle: typeof import('@ark-ui/vue')['DialogTitle']
    ArkHoverCard: typeof import('@ark-ui/vue')['HoverCard']
    ArkHoverCardArrow: typeof import('@ark-ui/vue')['HoverCardArrow']
    ArkHoverCardArrowTip: typeof import('@ark-ui/vue')['HoverCardArrowTip']
    ArkHoverCardContent: typeof import('@ark-ui/vue')['HoverCardContent']
    ArkHoverCardPositioner: typeof import('@ark-ui/vue')['HoverCardPositioner']
    ArkHoverCardTrigger: typeof import('@ark-ui/vue')['HoverCardTrigger']
    DarkModeToggle: typeof import('./src/features/core/components/DarkModeToggle.vue')['default']
    DarkMpdeToggle: typeof import('./src/features/core/components/DarkMpdeToggle.vue')['default']
    DynamicLayout: typeof import('./src/features/core/components/DynamicLayout.vue')['default']
    LoginForm: typeof import('./src/features/auth/components/LoginForm.vue')['default']
    OnboardingModal: typeof import('./src/features/user/components/OnboardingModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./src/features/user/components/SignupForm.vue')['default']
    TodoForm: typeof import('./src/features/todo/components/TodoForm.vue')['default']
    TodoList: typeof import('./src/features/todo/components/TodoList.vue')['default']
    UiButton: typeof import('./src/features/ui/components/buttons/UiButton.vue')['default']
    UiButtonBase: typeof import('./src/features/ui/components/buttons/UiButtonBase.vue')['default']
    UiCheckbox: typeof import('./src/features/ui/components/inputs/UiCheckbox.vue')['default']
    UiDrawer: typeof import('./src/features/ui/components/drawer/UiDrawer.vue')['default']
    UiDrawerContent: typeof import('./src/features/ui/components/drawer/UiDrawerContent.vue')['default']
    UiDrawerHeader: typeof import('./src/features/ui/components/drawer/UiDrawerHeader.vue')['default']
    UiFormControl: typeof import('./src/features/ui/components/forms/UiFormControl.vue')['default']
    UiFormError: typeof import('./src/features/ui/components/forms/UiFormError.vue')['default']
    UiFormLabel: typeof import('./src/features/ui/components/forms/UiFormLabel.vue')['default']
    UiGhostButton: typeof import('./src/features/ui/components/buttons/UiGhostButton.vue')['default']
    UiIcon: typeof import('./src/features/ui/components/UiIcon.vue')['default']
    UiIconButton: typeof import('./src/features/ui/components/buttons/UiIconButton.vue')['default']
    UiLinkButton: typeof import('./src/features/ui/components/buttons/UiLinkButton.vue')['default']
    UiModal: typeof import('./src/features/ui/components/modal/UiModal.vue')['default']
    UiModalContent: typeof import('./src/features/ui/components/modal/UiModalContent.vue')['default']
    UiModalHeader: typeof import('./src/features/ui/components/modal/UiModalHeader.vue')['default']
    UiPasswordInput: typeof import('./src/features/ui/components/inputs/UiPasswordInput.vue')['default']
    UiSwitch: typeof import('./src/features/ui/components/inputs/UiSwitch.vue')['default']
    UiTextInput: typeof import('./src/features/ui/components/inputs/UiTextInput.vue')['default']
  }
}
